_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
hotlink: true
origin: 'https://NY:Senate@live-nysenate-2022.pantheonsite.io'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
excluded_extensions: ''
