name: 'Billboard.js Charts'
type: module
description: 'Charts module integration with Billboard.js Charts.'
package: Charts
core: 8.x
core_version_requirement: ^8 || ^9
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2021-11-09
version: '8.x-3.3'
project: 'charts'
datestamp: 1636438367
