_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
hotlink: true
origin: 'https://live-nysenate-2022.pantheonsite.io'
origin_dir: sites/default/files
proxy_headers: ''
use_imagecache_root: true
verify: true
excluded_extensions: ''
