key.type.twitter_api_app:
  type: mapping
  label: 'Twitter API key type'
  mapping: []

key.input.twitter_api_app:
  type: mapping
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client secret'
    bearer_token:
      type: string
      label: 'Bearer token'
    access_token:
      type: string
      label: 'Access token'
    access_secret:
      type: string
      label: 'Access secret'
